use_frameworks!

platform :ios, '9.0'

target 'SYPermanentThread_Example' do
  pod 'SYPermanentThread', :path => '../'

  target 'SYPermanentThread_Tests' do
    inherit! :search_paths

    
  end
end
